# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-17 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processuser',
            name='role',
            field=models.IntegerField(choices=[(0, 'Process Manager'), (1, 'Process Member')], default=1),
        ),
    ]
