# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='progress',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
