# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-15 20:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_projectuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='end_Date',
            new_name='end_date',
        ),
    ]
